services:
  web:
    build: .
    container_name: bdaygo_web
    restart: always
    command: bash -c "
      flask --app manage.py init-db &&
      gunicorn -b 0.0.0.0:5000 wsgi:app"
    ports:
      - "5000:5000"
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - .:/usr/src/project
      - ./static:/usr/src/project/static
    networks:
      - bdaygo-network
#      - proxy-global-network  # Підключення до глобальної мережі

  redis:
    image: redis:alpine
    container_name: bdaygo_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - bdaygo-network

  celery_worker:
    build: .
    container_name: bdaygo_celery_worker
    command: celery -A celery_worker.celery worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - .:/usr/src/project
    networks:
      - bdaygo-network

  celery_beat:
    build: .
    container_name: bdaygo_celery_beat
    command: celery -A celery_worker.celery beat --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - .:/usr/src/project
    networks:
      - bdaygo-network

networks:
  bdaygo-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.55.0/24
#    proxy-global-network:
#      external: true

volumes:
  redis_data: